// let myString = "Hello, world!";
// console.log(myString); 
// console.log(typeof myString);
// let myNumber = 32;
// console.log(myNumber);
// console/log(typeof myNumber); 
// let myBoolean = true;
// console.log(myBoolean); 
// console.log(typeof myBoolean); 
// let myUndefined;
// console.log(myUndefined);
// console.log(typeof myUndefined); 
// let myNull = null;
// console.log(myNull); 
// console.log(typeof myNull); 
// let myObject = { name: "Rohit" };
// console.log(myObject);
// console.log(typeof myObject);
// let mySymbol =Symbol("AG");
// console.log("mySymbol); 
// console.log(typeof mySymbol);
// let myBigInt = 1234567890123456789012345678901234567890n;
// console.log(myBigInt); 
// console.log(typeof myBigInt); 
